# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wende.github.io" # the base hostname & protocol for your site

authors:
  wende:
    name: "Krzysztof Wende"
    description: "Krzysztof is a natural born leader. Charismatic and confident, holds the entire team together. He’s also a distributed systems designer and a functional programming guru. He’s passionate about uncovering fascinating pieces of state-of-the-art software and popularising them."
    stack: "Scalable and distributed development, System architecture, Elixir, Erlang, Scala, Node.js"
    link: "http://neontree.pl/wende"
    avatar: "img/wende_2.jpg"

  cichocinski:
    name: "Tomasz Cichocinski"
    description: "All kinds of front-end. Tomek is web development and game programming hothead, who's always trying to find best solutions and best tools for the given job. Spending all free time discovering new technologies and mastering already known. He's providing front-end expertise to the whole team."
    stack: "JavaScript, React, Redux, Elm, Node.js, Build systems"
    link: "http://neontree.pl/cichocinski"
    avatar: "img/cichocinski_2.jpg"

  hajto:
    name: "Jakub Hajto"
    stack: "Elixir, Phoenix WebFramework, Scala, Play, Akka, Jenkins, Docker, Continous Integration and Delivery, Third Party Services"
    description: "Functional Programming Ninja, he jumps between technologies to get the best out of them. Currently in love with Elixir’s simplicity and performance. At the same time he’s the laziest of us all. If something can be done without programmers interference, he’ll probably do it that way. That’s why he loves Jenkins and Docker."
    stack: "Elixir, Phoenix WebFramework, Scala, Play, Akka, Jenkins, Docker, Continous Integration and Delivery, Third Party Services"
    link: "http://neontree.pl/hajto"
    avatar: "img/hajto_2.jpg"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: "I hate Monads"
  subtitle: "Neon Tree Solutions Ltd official blog"
  avatar: "avatar.png"
  #gravatar: "502d830e6e95833ce07efc51f89a38e6" # Email MD5 hash
  description: "How to function in a [dys]functional world" # used by search engines

  # Header and footer text
  header_text: >
     <p id="quote">How to function in a [dys]functional world</p>

  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a><br><a href="http://eepurl.com/bzH3Mr"> Subscribe to the newsletter </a>

  # Icons
  rss: false
  email_address: "contact@neontree.pl" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "wende"
  google_plus: "https://plus.google.com/+KrzysztofWendeIraasta"
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: "http://stackoverflow.com/users/2086804/krzysztof-wende" # Full URL
  steam:
  tumblr:
  twitter: "iraasta"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-56241713-9" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "iraasta"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,700italic,400italic|Inconsolata:400"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins:
    - jekyll-sitemap
    - jekyll-gist
    - jekyll-seo-tag
    - jekyll-paginate
exclude: [vendor]
